apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: project-template
  annotations:
    description: "Create the project and namespace"
parameters:
  - name: PROJECT
    description: The name of the project
  - name: USER
    description: user with rights to launch b/r pipelines
objects:
# htpasswd -c -B -b passwd_file test01 passw0rd
# to reuse htpaasswd
# htpasswd  -B -b ~/OADP/passwd_file test03 passw0rd
# https://www.redhat.com/sysadmin/openshift-htpasswd-oauth
- kind: User
  apiVersion: user.openshift.io/v1
  metadata:
    name: ${USER}
  identities:
    - 'htpasswd:${USER}'
  groups: null

# give the new user self provisioning role
- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: ${USER}-selfprovisioning
    namespace: ${PROJECT}
  subjects:
    - kind: User
      apiGroup: rbac.authorization.k8s.io
      name: ${USER}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: self-provisioner

