apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: oadp-edge
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: ghcr.io/kaovilai/oadp-operator-catalog:edge
  displayName: Tiger's OADP Edge
  publisher: Tiger Kaovilai
  updateStrategy:
    registryPoll:
      interval: 30m
