apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: oadp-edge
  namespace: operator
spec:
  sourceType: grpc
  image: ghcr.io/kaovilai/oadp-operator-catalog:edge
  displayName: Tiger's OADP Edge Catalog
  publisher: Tiger Kaovilai
  updateStrategy:
    registryPoll:
      interval: 30m
