apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    openshift.io/cluster-monitoring: "true"
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        volumeMounts:
          - mountPath: /var/run/secrets/openshift/serviceaccount
            name: bound-sa-token
            readOnly: true
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: REGISTRY
            value: quay.io
          - name: PROJECT
            value: konveyor
          - name: VELERO_REGISTRY_REPO
            value: registry
          - name: VELERO_REGISTRY_TAG
            value: latest
          - name: VELERO_REPO
            value: velero
          - name: VELERO_OPENSHIFT_PLUGIN_REPO
            value: openshift-velero-plugin
          - name: VELERO_OPENSHIFT_PLUGIN_TAG
            value: latest
          - name: VELERO_RESTIC_RESTORE_HELPER_REPO
            value: velero-restic-restore-helper
          - name: VELERO_AWS_PLUGIN_REPO
            value: velero-plugin-for-aws
          - name: VELERO_GCP_PLUGIN_REPO
            value: velero-plugin-for-gcp
          - name: VELERO_AZURE_PLUGIN_REPO
            value: velero-plugin-for-microsoft-azure
          - name: VELERO_KUBEVIRT_PLUGIN_REPO
            value: kubevirt-velero-plugin
          - name: VELERO_CSI_PLUGIN_REPO
            value: velero-plugin-for-csi
          - name: VELERO_TAG
            value: latest
          - name: VELERO_RESTIC_RESTORE_HELPER_TAG
            value: latest
          - name: VELERO_AWS_PLUGIN_TAG
            value: latest
          - name: VELERO_GCP_PLUGIN_TAG
            value: latest
          - name: VELERO_AZURE_PLUGIN_TAG
            value: latest
          - name: VELERO_CSI_PLUGIN_TAG
            value: latest
          - name: VELERO_KUBEVIRT_PLUGIN_TAG
            value: v0.2.0
          - value: quay.io/konveyor/velero:latest
            name: RELATED_IMAGE_velero
          - value: quay.io/konveyor/velero-restic-restore-helper:latest
            name: RELATED_IMAGE_velero_restic_restore_helper
          - value: quay.io/konveyor/openshift-velero-plugin:latest
            name: RELATED_IMAGE_openshift_plugin
          - value: quay.io/konveyor/velero-plugin-for-aws:latest
            name: RELATED_IMAGE_aws_plugin
          - value: quay.io/konveyor/velero-plugin-for-microsoft-azure:latest
            name: RELATED_IMAGE_azure_plugin
          - value: quay.io/konveyor/velero-plugin-for-gcp:latest
            name: RELATED_IMAGE_gcp_plugin
          - value: quay.io/konveyor/velero-plugin-for-csi:latest
            name: RELATED_IMAGE_csi_plugin
          - value: quay.io/konveyor/registry:latest
            name: RELATED_IMAGE_registry
          - value: quay.io/konveyor/kubevirt-velero-plugin:v0.2.0
            name: RELATED_IMAGE_kubevirt_plugin
        args:
        - --leader-elect
        image: controller:latest
        imagePullPolicy: Always
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        startupProbe:
          httpGet:
            path: /healthz
            port: 8081
          failureThreshold: 12
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 128Mi
      serviceAccountName: controller-manager
      volumes:
      - name: bound-sa-token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 3600
              audience: openshift
      terminationGracePeriodSeconds: 10
