apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    openshift.io/cluster-monitoring: "true"
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        volumeMounts:
          - mountPath: /var/run/secrets/openshift/serviceaccount
            name: bound-sa-token
            readOnly: true
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: RELATED_IMAGE_velero
            value: quay.io/konveyor/velero:konveyor-1.9
          - name: RELATED_IMAGE_velero-restic-restore-helper
            value: quay.io/konveyor/velero-restic-restore-helper:konveyor-1.9
          - name: RELATED_IMAGE_openshift-velero-plugin
            value: quay.io/konveyor/openshift-velero-plugin:latest
          - name: RELATED_IMAGE_velero-plugin-for-aws
            value: quay.io/konveyor/velero-plugin-for-aws:konveyor-1.5
          - name: RELATED_IMAGE_velero-plugin-for-microsoft-azure
            value: quay.io/konveyor/velero-plugin-for-microsoft-azure:konveyor-1.5
          - name: RELATED_IMAGE_velero-plugin-for-gcp
            value: quay.io/konveyor/velero-plugin-for-gcp:konveyor-1.5
          - name: RELATED_IMAGE_velero-plugin-for-csi
            value: quay.io/konveyor/velero-plugin-for-csi:konveyor-0.3
          - name: RELATED_IMAGE_volume-snapshot-mover
            value: quay.io/konveyor/volume-snapshot-mover:latest
          - name: RELATED_IMAGE_kubevirt-velero-plugin
            value: quay.io/konveyor/kubevirt-velero-plugin:v0.2.0
        args:
        - --leader-elect
        image: controller:latest
        imagePullPolicy: Always
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        startupProbe:
          httpGet:
            path: /healthz
            port: 8081
          failureThreshold: 12
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 128Mi
      serviceAccountName: controller-manager
      volumes:
      - name: bound-sa-token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 3600
              audience: openshift
      terminationGracePeriodSeconds: 10
