name: Bug Report
description: File a bug report
title: "Bug: "
labels: ["kind/bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening a bug with OADP, our bug tracking has moved to [jira](https://issues.redhat.com/projects/OADP/issues)
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
       

