---
# This manifest gives tekton the permission to execute velero backups and restore 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oadp-nonadmin-role
rules:
- apiGroups:
  - velero.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
# This role gives a non-admin user permission to execute tekton pipelines, but
# not to edit the pipeline.
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-runner
rules:
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns"]
  verbs: ["*"]
