apiVersion: oadp.openshift.io/v1alpha1
kind: Velero
metadata:
  name: velero-sample
spec:
  defaultVeleroPlugins:
  - openshift
  - aws
  backupStorageLocations:
  - provider: aws
    default: true
    objectStorage:
      bucket: my-bucket-name
      prefix: my-prefix
    config:
      region: us-east-1
      profile: "default"
    credential:
      name: cloud-credentials
      key: cloud
  volumeSnapshotLocations:
    - provider: aws
      config:
        region: us-west-2
        profile: "default"
  enableRestic: true