apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: project-template
  annotations:
    description: "Create the project and namespace"
parameters:
  - name: PROJECT
    description: The name of the project
  - name: USER
    description: user with rights to launch b/r pipelines
objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: ${PROJECT}

- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: view
    namespace: ${PROJECT}
  subjects:
    - kind: User
      apiGroup: rbac.authorization.k8s.io
      name: ${USER}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view
  name: view