apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: project-template
  annotations:
    description: "Create the project and namespace"
parameters:
  - name: BASENAME
    description: The name of the project
    value: foo
  - name: USER
    description: user with rights to launch pipelines
objects:
  - kind: User
    apiVersion: user.openshift.io/v1
    metadata:
      name: '${USER}'
    identities:
      - '${BASENAME}:${USER}'


