name: docs-actions
on:
  schedule:
  - cron: "0 0 1/7 * *" #“At 00:00 on every 7th day-of-month from 1 through 31.”
  pull_request:
    paths:
    - '**/**.md'
    - '.github/workflows/docs-actions.yml' #check changes to this action
    paths-ignore:
    - 'vendor/**' #don't check vendor docs
    #appears workflow check doesn't work or get ignored.
jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.0.8
      with:
        args: --verbose --no-progress **/*.md
    - run: if grep 'Errors in' ./lychee/out.md; then fail; fi
