name: docs-actions
on:
  pull_request:
    paths:
      - '**/**.md'
jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.0.8
      with:
        args: --verbose --no-progress **/*.md
#       env:
#         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

#     - name: Create Issue From File
#       uses: peter-evans/create-issue-from-file@v3
#       with:
#         title: Link Checker Report
#         content-filepath: ./lychee/out.md
#         labels: report, automated issue
    - run: if grep 'Errors in' ./lychee/out.md; then fail fi
