name: go-tests
on:
  push:
    paths:
      - '**/**.go'
      - '**/go.mod'
      - '.github/workflows/go-tests.yml'
      - '**/Dockerfile'
  pull_request:
    paths:
      - '**/**.go'
      - '**/go.mod'
      - '.github/workflows/go-tests.yml'
      - '**/Dockerfile'
jobs:
  make-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.6' # The Go version to download (if necessary) and use.
    - run: go version
    - run: make test
    # Update Coverage badge if not already
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: coverage badge
        file_pattern: coverage_badge.svg
        commit_user_name: Coverage Badge Bot
        commit_user_email: actions@github.com


  podman-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: podman build .