name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        - base: master
          head: master
        - base: oadp-1.1
          head: oadp-1.1
        - base: oadp-1.0
          head: oadp-1.0
      fail-fast: false
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: openshift
          base: ${{ matrix.base }}
          head: ${{ matrix.head }}